// Privacy Policy page modeled after TermsPage
import { useState, useEffect } from 'react';
import { acceptPrivacy, hasAcceptedPrivacy } from '../services/tosService';
import { burstConfetti } from '../services/confetti';
import { Dumbbell } from 'lucide-react';
import './Terms.css';

export default function PrivacyPage() {
  const initialAccepted = hasAcceptedPrivacy(undefined);
  const [agreed, setAgreed] = useState(initialAccepted);

  const [accepted, setAccepted] = useState(initialAccepted);

  useEffect(() => {
    const onAccepted = () => {
      setAccepted(true);
      setAgreed(true);
    };
    window.addEventListener('fitbuddy-privacy-accepted', onAccepted);
    return () => window.removeEventListener('fitbuddy-privacy-accepted', onAccepted);
  }, []);

  const onAccept = () => {
    if (!agreed) return;
    acceptPrivacy(undefined);
    setAccepted(true);
    try { burstConfetti({count: 36}); } catch (e) { /* noop */ }
    try {
      const raw = localStorage.getItem('fitbuddy_user_data');
      const userId = raw ? (JSON.parse(raw).data?.id || null) : null;
      if (userId) {
        import('../services/apiAuth').then(m => m.attachAuthHeaders({ method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId, accepted_privacy: true }) })).then(init => fetch('/api/userdata/save', init)).catch(()=>{});
      }
    } catch (e) {}
  };

  return (
    <div className="terms-page">
      <header className="terms-hero">
        <div className="terms-hero-inner">
          <div className="hero-logo"><Dumbbell size={36} color="#fff" /></div>
          <div>
            <h1 className="hero-title">FitBuddy Privacy Policy</h1>
            <p className="hero-sub">How we collect, use, and protect your data — short summary.</p>
          </div>
        </div>
      </header>

      <main className="terms-container">
        <article className="terms-card">
          <h2>Data We Collect</h2>
          <p>We collect workout preferences, profile details, and optionally account information when you sign up. We do not collect sensitive medical data unless you explicitly provide it.</p>
        </article>

        <article className="terms-card">
          <h2>How We Use Data</h2>
          <p>Data is used to personalize workout plans, sync across devices, and improve the service. We may use aggregated, anonymized data for analytics.</p>
        </article>

        <article className="terms-card">
          <h2>Sharing & Third Parties</h2>
          <p>We do not sell personal data. We may share data with service providers who assist in backup, analytics, or authentication, under appropriate agreements.</p>
        </article>

        <article className="terms-card">
          <h2>Security</h2>
          <p>We use industry-standard measures to secure data but cannot guarantee absolute security. Follow secure practices and protect your account credentials.</p>
        </article>
      </main>

      <section className="terms-full">
        <div className="terms-full-inner">
          <h2>Full Privacy Policy</h2>
          <p>This Privacy Policy explains how FitBuddy, LLC collects, uses, discloses, and protects the personal information of users of the Service. By using the Service you consent to the collection and use of information as described in this policy.</p>

          <h3>1. Information We Collect</h3>
          <p>We collect information you provide directly (profile, email, preferences), information generated by your use of the Service (workout logs, settings), and technical information (device, browser, IP) to operate and improve the Service.</p>

          <h3>2. Use of Information</h3>
          <p>Information is used to personalize content, provide support, enable backups (when opted-in), deliver notifications, and prevent abuse.</p>

          <h3>3. Sharing and Disclosure</h3>
          <p>We may share information with vendors who perform services for us, comply with legal obligations, or protect our rights. Aggregated or anonymized data may be used for research or analytics.</p>

          <h3>4. Data Retention and Rights</h3>
          <p>We retain data as long as necessary to provide the Service or as required by law. Users may request deletion or access to their data by contacting support.</p>

          <h3>5. International Transfers</h3>
          <p>Data may be processed in different jurisdictions. We take measures to protect data when transferring across borders.</p>

          <h3>6. Changes to Privacy Policy</h3>
          <p>We may update this Privacy Policy and will provide notice for material changes. Continued use after updates constitutes acceptance.</p>

          <p><em>Effective Date:</em> The effective date is the date you first use the Service. For privacy questions, contact our support team.</p>
        </div>
      </section>

      <div className="terms-cta-bottom">
        <div className="terms-cta-inner">
          <label className="terms-checkbox">
            <input type="checkbox" checked={agreed} onChange={(e) => setAgreed(e.target.checked)} />
            <span>I have read and agree to the Privacy Policy</span>
          </label>
        </div>
        <div className="terms-cta-inner stack">
          <button className={"btn btn-primary btn-lg" + (accepted ? ' accepted-btn' : '')} onClick={onAccept} disabled={!agreed || accepted} aria-disabled={!agreed || accepted}>{accepted ? 'Accepted' : 'Accept'}</button>
        </div>
      </div>
    </div>
  );
}
