import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Target, Calendar, Zap } from 'lucide-react';
import './WelcomePage.css';
import Footer from './Footer';
import IntroBubbles from './IntroBubbles';


// Only generate random features once per page load
const features = ["Set Goals", "Track Progress", "Plan Workouts", "Stay Motivated", "AI Powered", "Fun & Easy", "Personalized"];
const random: number[] = [];
while (random.length < 3) {
  const idx = Math.floor(Math.random() * 7);
  if (!random.includes(idx)) {
    random.push(idx);
  }
}

const WelcomePage: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  // Parse query param
  const params = new URLSearchParams(location.search);
  const introParam = params.get('intro');
  const shouldShowIntro = introParam === null || introParam === '1';
  const [showMain, setShowMain] = useState(!shouldShowIntro);
  // When intro=0 we still render the main content but avoid entrance animations
  const shouldAnimateLogo = introParam !== '0';

  // When intro finishes, remove ?intro from URL
  const handleIntroFinish = () => {
    setShowMain(true);
    if (location.search.includes('intro')) {
      navigate('/', { replace: true });
    }
  };
  return (
    <div className="welcome-page">
      {!showMain && <IntroBubbles onFinish={handleIntroFinish} />}
      {showMain && (
        <>
          {/* Hero Section */}
          <div className="hero-section">
            <div className="hero-content">
                <div className={"logo-section" + (shouldAnimateLogo ? " bounce-in" : "") }>
                {/* Centered logo above the title */}
                <div className="logo logo-centered">
                  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-dumbbell"><path d="m6.5 6.5 11 11"></path><path d="m21 21-1-1"></path><path d="m3 3 1 1"></path><path d="m18 22 4-4"></path><path d="m2 6 4-4"></path><path d="m3 10 7-7"></path><path d="m14 21 7-7"></path></svg>
                </div>
                <h1 className="app-title">Fitbuddy</h1>
                <p className="app-subtitle">Your AI-Powered Fitness Companion</p>
              </div>
              <div className="hero-text fade-in-up">
                <h2>Transform Your Fitness Journey</h2>
                <p>Get personalized workout plans powered by AI, track your progress, and achieve your fitness goals with fun, gamified experience.</p>
              </div>
              <div className="cta-section fade-in-up">
                <Link to="/questionnaire" className="btn btn-primary btn-large">
                  Start Your Journey
                </Link>
                <p className="cta-subtitle">Free • Personalized • AI-Powered</p>
              </div>
            </div>
            <div className="hero-illustration">
              <div className="floating-card card-1">
                <Target size={24} />
                <span>{features[random[0]]}</span>
              </div>
              <div className="floating-card card-2">
                <Calendar size={24} />
                <span>{features[random[1]]}</span>
              </div>
              <div className="floating-card card-3">
                <Zap size={24} />
                <span>{features[random[2]]}</span>
              </div>
            </div>
          </div>
          {/* Features Section */}
          <div className="features-section">
            <div className="container">
              <h3 className="section-title">Why Choose Fitbuddy?</h3>
              <div className="features-grid">
                <div className="feature-card card fade-in-up">
                  <div className="feature-icon">
                    <Target size={32} />
                  </div>
                  <h4>AI-Powered Plans</h4>
                  <p>Get personalized workout routines generated by advanced AI based on your goals, fitness level, and preferences.</p>
                </div>
                <div className="feature-card card fade-in-up">
                  <div className="feature-icon">
                    <Calendar size={32} />
                  </div>
                  <h4>Smart Calendar</h4>
                  <p>Visualize your workout schedule with an intuitive calendar. Easily modify or request new workouts for any day.</p>
                </div>
                <div className="feature-card card fade-in-up">
                  <div className="feature-icon">
                    <Zap size={32} />
                  </div>
                  <h4>Adaptive Training</h4>
                  <p>Your workouts evolve with you. The AI adjusts difficulty and variety based on your progress and feedback.</p>
                </div>
              </div>
            </div>
          </div>
          {/* How It Works Section */}
          <div className="how-it-works-section">
            <div className="container">
              <h3 className="section-title">How It Works</h3>
              <div className="steps-container">
                <div className="step">
                  <div className="step-number">1</div>
                  <div className="step-content">
                    <h4>Tell Us About You</h4>
                    <p>Answer a few questions about your fitness goals, experience level, and preferences.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-number">2</div>
                  <div className="step-content">
                    <h4>Get Your AI Plan</h4>
                    <p>Our AI creates a personalized 30-day workout calendar tailored specifically for you.</p>
                  </div>
                </div>
                <div className="step">
                  <div className="step-number">3</div>
                  <div className="step-content">
                    <h4>Train & Adapt</h4>
                    <p>Follow your workouts, track progress, and request changes whenever you need them.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* CTA Section */}
          <div className="final-cta-section">
            <div className="container">
              <div className="final-cta-content">
                <h3>Ready to Transform Your Fitness?</h3>
                <p>Join thousands of users who have already started their journey with Fatbuddy.</p>
                <Link to="/questionnaire" className="btn btn-primary btn-large">
                  Get Started Now
                </Link>
              </div>
            </div>
          </div>
        </>
      )}
      <div className="welcome-footer-spacer">
        <Footer />
      </div>
    </div>
  );
};

export default WelcomePage;